import { FormEvent, useEffect, useMemo, useState } from 'react';
import { gateway, type Session } from '../api/gateway';

type Item = { _id: string; name?: string; firstName?: string; lastName?: string; email?: string; section?: string; academicYear?: string; classId?: string };
const label = (item: Item) => item.name ?? [item.firstName, item.lastName].filter(Boolean).join(' ') ?? item.email ?? item._id;

export function AssignmentsPage({ session }: { session: Session }) {
  const [classes, setClasses] = useState<Item[]>([]); const [subjects, setSubjects] = useState<Item[]>([]); const [teachers, setTeachers] = useState<Item[]>([]); const [rows, setRows] = useState<Item[]>([]); const [open, setOpen] = useState(false); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const [form, setForm] = useState({ title: '', description: '', classId: '', subjectId: '', teacherId: '', dueDate: '' });
  async function load() { try { const [a,b,c,d] = await Promise.all([gateway<Item[]>('/assignments',{},session.access_token),gateway<Item[]>('/classes',{},session.access_token),gateway<Item[]>('/subjects',{},session.access_token),gateway<Item[]>('/teachers',{},session.access_token)]); setRows(a);setClasses(b);setSubjects(c);setTeachers(d); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load assignments.'); } }
  useEffect(()=>{void load();},[session.access_token]); const classSubjects = useMemo(()=>subjects.filter((s)=>s.classId===form.classId),[subjects,form.classId]);
  async function submit(e: FormEvent) { e.preventDefault(); setBusy(true);setError(''); try { await gateway('/assignments',{method:'POST',body:JSON.stringify({...form,dueDate:new Date(form.dueDate).toISOString()})},session.access_token);setOpen(false);setForm({title:'',description:'',classId:'',subjectId:'',teacherId:'',dueDate:''});await load(); } catch (x) { setError(x instanceof Error?x.message:'Unable to create assignment.'); } finally {setBusy(false);} }
  return <><div className="page-intro"><div><p>Assignments, submissions and grading.</p><small>Data is loaded from <code>/assignments</code>.</small></div><div className="toolbar"><button className="secondary" onClick={()=>void load()}>Refresh</button><button className="primary" onClick={()=>setOpen(true)}>Create assignment</button></div></div>{open&&<section className="composer structured-composer"><div><h2>Create assignment</h2><p>Set the instructions, class, subject, teacher and due date.</p></div><form className="structured-form" onSubmit={(e)=>void submit(e)}><label>Title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Class<select required value={form.classId} onChange={e=>setForm({...form,classId:e.target.value,subjectId:''})}><option value="">Choose a class</option>{classes.map(x=><option key={x._id} value={x._id}>{label(x)} {x.section?`— ${x.section}`:''}</option>)}</select></label><label className="full">Description<textarea required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Subject<select required value={form.subjectId} disabled={!form.classId} onChange={e=>setForm({...form,subjectId:e.target.value})}><option value="">Choose a subject</option>{classSubjects.map(x=><option key={x._id} value={x._id}>{label(x)}</option>)}</select></label><label>Teacher<select required value={form.teacherId} onChange={e=>setForm({...form,teacherId:e.target.value})}><option value="">Choose a teacher</option>{teachers.map(x=><option key={x._id} value={x._id}>{label(x)}</option>)}</select></label><label>Due date<input required type="date" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/></label><div className="form-actions"><button className="secondary" type="button" onClick={()=>setOpen(false)}>Cancel</button><button className="primary" disabled={busy}>{busy?'Sending…':'Send to API'}</button></div></form></section>}{error&&<div className="state error"><span>{error}</span></div>}<section className="data-card"><div className="data-top"><h2>Live records</h2></div><div className="table-wrap"><table><tbody>{rows.map(r=><tr key={r._id}><td>{label(r)}</td></tr>)}</tbody></table></div></section></>;
}
