import { FormEvent, useEffect, useMemo, useState } from 'react';
import { gateway, type Session } from '../api/gateway';

type Item = { _id: string; name?: string; title?: string; description?: string; firstName?: string; lastName?: string; email?: string; section?: string; academicYear?: string; classId?: string; subjectId?: string; teacherId?: string; dueDate?: string };
const label = (item: Item) => (item.name ?? item.title ?? [item.firstName, item.lastName].filter(Boolean).join(' ')) || item.email || item._id || 'Unknown';

export function AssignmentsPage({ session }: { session: Session }) {
  const isAdmin = session.user.role === 'admin';
  const [classes, setClasses] = useState<Item[]>([]); const [subjects, setSubjects] = useState<Item[]>([]); const [teachers, setTeachers] = useState<Item[]>([]); const [rows, setRows] = useState<Item[]>([]); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<Item | null>(null); const [deletingId, setDeletingId] = useState<string | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const [form, setForm] = useState({ title: '', description: '', classId: '', subjectId: '', teacherId: '', dueDate: '' });
  async function load() { try { const [a,b,c,d] = await Promise.all([gateway<Item[]>('/assignments',{},session.access_token),gateway<Item[]>('/classes',{},session.access_token),gateway<Item[]>('/subjects',{},session.access_token),gateway<Item[]>('/teachers',{},session.access_token)]); setRows(a);setClasses(b);setSubjects(c);setTeachers(d); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load assignments.'); } }
  useEffect(()=>{void load();},[session.access_token]); const classSubjects = useMemo(()=>subjects.filter((s)=>s.classId===form.classId),[subjects,form.classId]);
  function beginEdit(item: Item) { setEditing(item); setForm({ title: item.title ?? '', description: item.description ?? '', classId: item.classId ?? '', subjectId: item.subjectId ?? '', teacherId: item.teacherId ?? '', dueDate: item.dueDate?.slice(0, 10) ?? '' }); setOpen(true); }
  async function remove(item: Item) { if (!window.confirm(`Are you sure you want to delete ${label(item)}? This cannot be undone.`)) return; setDeletingId(item._id); try { await gateway(`/assignments/${item._id}`, { method: 'DELETE' }, session.access_token); setRows((items) => items.filter((row) => row._id !== item._id)); } catch (x) { setError(x instanceof Error ? x.message : 'Unable to delete assignment.'); } finally { setDeletingId(null); } }
  async function submit(e: FormEvent) { e.preventDefault(); setBusy(true);setError(''); try { const saved = await gateway<Item>(editing ? `/assignments/${editing._id}` : '/assignments',{method:editing?'PATCH':'POST',body:JSON.stringify({...form,dueDate:new Date(form.dueDate).toISOString()})},session.access_token); setRows((items) => editing ? items.map((item) => item._id === saved._id ? saved : item) : [saved, ...items]); setOpen(false);setEditing(null);setForm({title:'',description:'',classId:'',subjectId:'',teacherId:'',dueDate:''}); } catch (x) { setError(x instanceof Error?x.message:'Unable to save assignment.'); } finally {setBusy(false);} }
  return <><div className="page-intro"><div><p>Assignments, submissions and grading.</p><small>Data is loaded from <code>/assignments</code>.</small></div><div className="toolbar"><button className="secondary" onClick={()=>void load()}>Refresh</button><button className="primary" onClick={()=>{setEditing(null);setOpen(true);}}>Create assignment</button></div></div>{open&&<section className="composer structured-composer"><div><h2>{editing?'Edit assignment':'Create assignment'}</h2><p>Set the instructions, class, subject, teacher and due date.</p></div><form className="structured-form" onSubmit={(e)=>void submit(e)}><label>Title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Class<select required value={form.classId} onChange={e=>setForm({...form,classId:e.target.value,subjectId:''})}><option value="">Choose a class</option>{classes.map(x=><option key={x._id} value={x._id}>{label(x)} {x.section?`— ${x.section}`:''}</option>)}</select></label><label className="full">Description<textarea required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Subject<select required value={form.subjectId} disabled={!form.classId} onChange={e=>setForm({...form,subjectId:e.target.value})}><option value="">Choose a subject</option>{classSubjects.map(x=><option key={x._id} value={x._id}>{label(x)}</option>)}</select></label><label>Teacher<select required value={form.teacherId} onChange={e=>setForm({...form,teacherId:e.target.value})}><option value="">Choose a teacher</option>{teachers.map(x=><option key={x._id} value={x._id}>{label(x)}</option>)}</select></label><label>Due date<input required type="date" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/></label><div className="form-actions"><button className="secondary" type="button" onClick={()=>setOpen(false)}>Cancel</button><button className="primary" disabled={busy}>{busy?'Sending…':'Save changes'}</button></div></form></section>}{error&&<div className="state error"><strong>Couldn’t load assignments.</strong><span>{error}</span><button className="secondary" onClick={()=>void load()}>Try again</button></div>}<section className="data-card"><div className="data-top"><h2>Live records</h2></div><div className="table-wrap"><table><thead><tr><th>Title</th><th>Description</th><th>Due date</th>{isAdmin&&<th>Actions</th>}</tr></thead><tbody>{rows.map(r=><tr key={r._id}><td>{label(r)}</td><td>{r.description || '—'}</td><td>{r.dueDate ? new Date(r.dueDate).toLocaleDateString() : '—'}</td>{isAdmin&&<td><button className="secondary" onClick={()=>beginEdit(r)}>Edit</button><button className="danger-button" onClick={()=>void remove(r)} disabled={deletingId===r._id}>{deletingId===r._id?'Deleting…':'Delete'}</button></td>}</tr>)}</tbody></table></div></section></>;
}
