import { FormEvent, useEffect, useMemo, useState } from 'react';
import { gateway, type Session } from '../api/gateway';
import '../components/ClassesSubjectsPage.css';

type ModuleId = 'students'|'teachers'|'timetables'|'attendance'|'exams'|'fees'|'leave'|'admissions'|'certificates'|'notices'|'library'|'transport';
type Row = Record<string, unknown> & { _id: string };
type Props = { id: ModuleId; title: string; endpoint: string; action: string; session: Session };
const richName = (x: Row) => {
  const person = [x.firstName ?? x.applicantFirstName, x.lastName ?? x.applicantLastName].filter(Boolean).join(' ');
  if (x.studentId && x.date) return `Attendance — ${x.date} • ${x.status ?? 'unmarked'}`;
  if (x.dayOfWeek) return `Timetable — ${x.dayOfWeek} • ${Array.isArray(x.periods) ? x.periods.length : 0} period(s)`;
  if (x.feeType) return `Fee: ${x.feeType} • ${x.academicYear ?? 'Academic year not set'} • ₹${x.amount ?? 0}`;
  if (x.applicantFirstName) return `Admission: ${person} • ${x.status ?? 'pending'} • Guardian: ${x.guardianName ?? '—'}`;
  if (x.type && x.issuedDate) return `Certificate: ${x.type} • Issued ${new Date(String(x.issuedDate)).toLocaleDateString()}`;
  const label = x.name || x.routeName || x.title || x.type || x.examType || x.rollNumber || person || x.guardianName || x.email;
  return String(label || 'Unnamed record');
};
const name = (x: Row) => String(x.name ?? [x.firstName, x.lastName].filter(Boolean).join(' ') ?? x.email ?? x._id);
const toIso = (v: FormDataEntryValue | null) => v ? new Date(String(v)).toISOString() : undefined;

export function StructuredResourcePage({ id, title, endpoint, action, session }: Props) {
  const [rows,setRows]=useState<Row[]>([]),[classes,setClasses]=useState<Row[]>([]),[subjects,setSubjects]=useState<Row[]>([]),[teachers,setTeachers]=useState<Row[]>([]),[students,setStudents]=useState<Row[]>([]);
  const [open,setOpen]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[selectedClass,setSelectedClass]=useState(''),[periods,setPeriods]=useState([{periodNumber:1,subjectId:'',teacherId:'',startTime:'09:00',endTime:'09:45'}]),[stops,setStops]=useState([{stopName:'',pickupTime:'07:30'}]),[attendance,setAttendance]=useState<Record<string,string>>({});
  const need = id==='students'||id==='teachers'||id==='timetables'||id==='attendance'||id==='exams'||id==='fees'||id==='leave'||id==='admissions'||id==='certificates'||id==='notices';
  async function load(){setError('');try{const req:Promise<Row[]>[]=[gateway<Row[]>(endpoint,{},session.access_token)];if(need)req.push(gateway<Row[]>('/classes',{},session.access_token),gateway<Row[]>('/subjects',{},session.access_token),gateway<Row[]>('/teachers',{},session.access_token),gateway<Row[]>('/students',{},session.access_token));const [data,c,s,t,st]=await Promise.all(req);setRows(data);if(c){setClasses(c);setSubjects(s!);setTeachers(t!);setStudents(st!);}}catch(e){setError(e instanceof Error?e.message:'Unable to load data.');}}
  useEffect(()=>{void load();},[endpoint,session.access_token]);
  const classSubjects=useMemo(()=>subjects.filter(s=>!selectedClass||s.classId===selectedClass),[subjects,selectedClass]); const classStudents=useMemo(()=>students.filter(s=>s.classId===selectedClass),[students,selectedClass]);
  function refs(){return <><label>Class<select required value={selectedClass} onChange={e=>{setSelectedClass(e.target.value);setAttendance({});}}><option value="">Choose a class</option>{classes.map(x=><option key={x._id} value={x._id}>{name(x)} {x.section?`— ${x.section}`:''}</option>)}</select></label></>}
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);let body:Record<string,unknown>={};const text=(k:string)=>String(f.get(k)??'').trim();try{
    if(id==='students') body={firstName:text('firstName'),lastName:text('lastName'),email:text('email'),phone:text('phone')||undefined,address:text('address')||undefined,dateOfBirth:toIso(f.get('dateOfBirth')),gender:text('gender')||undefined,rollNumber:text('rollNumber')||undefined,classId:text('classId')||undefined,section:text('section')||undefined,guardianName:text('guardianName')||undefined,guardianPhone:text('guardianPhone')||undefined,guardianEmail:text('guardianEmail')||undefined};
    if(id==='teachers') body={firstName:text('firstName'),lastName:text('lastName'),email:text('email'),phone:text('phone')||undefined,qualification:text('qualification')||undefined,subjectsHandled:f.getAll('subjectsHandled').map(String),joiningDate:toIso(f.get('joiningDate'))};
    if(id==='timetables') body={classId:selectedClass,dayOfWeek:text('dayOfWeek'),periods:periods.map(p=>({...p,periodNumber:Number(p.periodNumber)}) )};
    if(id==='attendance') body={classId:selectedClass,date:text('date'),records:classStudents.map(s=>({studentId:s._id,status:attendance[s._id]??'present'}))};
    if(id==='exams') body={name:text('name'),classId:selectedClass,subjectId:text('subjectId'),examDate:toIso(f.get('examDate')),maxMarks:Number(text('maxMarks')),examType:text('examType')};
    if(id==='fees') body={classId:selectedClass,academicYear:text('academicYear'),feeType:text('feeType'),amount:Number(text('amount')),dueDate:toIso(f.get('dueDate'))};
    if(id==='leave') body={requesterType:text('requesterType'),requesterId:text('requesterId'),fromDate:toIso(f.get('fromDate')),toDate:toIso(f.get('toDate')),reason:text('reason')};
    if(id==='admissions') body={applicantFirstName:text('applicantFirstName'),applicantLastName:text('applicantLastName'),dateOfBirth:toIso(f.get('dateOfBirth')),gender:text('gender'),guardianName:text('guardianName'),guardianContact:text('guardianContact'),guardianEmail:text('guardianEmail'),appliedClassId:selectedClass};
    if(id==='certificates') body={studentId:text('studentId'),type:text('type')};
    if(id==='notices') body={title:text('title'),message:text('message'),targetRole:text('targetRole')||undefined,targetClassId:text('targetClassId')||undefined};
    if(id==='library') body={title:text('title'),author:text('author'),isbn:text('isbn'),category:text('category'),totalCopies:Number(text('totalCopies'))};
    if(id==='transport') body={routeName:text('routeName'),vehicleNumber:text('vehicleNumber'),driverName:text('driverName'),driverContact:text('driverContact'),stops};
    await gateway(endpoint,{method:'POST',body:JSON.stringify(body)},session.access_token);setOpen(false);await load();
  }catch(x){setError(x instanceof Error?x.message:'Unable to create record.');}finally{setBusy(false);}}
  const field=(label:string,key:string,type='text',required=true)=><label>{label}<input name={key} type={type} required={required}/></label>;
  const lookup=(labelText:string,key:string,items:Row[],required=true)=><label>{labelText}<select name={key} required={required}><option value="">Choose {labelText.toLowerCase()}</option>{items.map(x=><option key={x._id} value={x._id}>{name(x)}</option>)}</select></label>;
  function form(){if(id==='students')return <>{field('First Name','firstName')}{field('Last Name','lastName')}{field('Email','email','email')}{field('Phone','phone')}{field('Address','address')}{field('Date of Birth','dateOfBirth','date',false)}<label>Gender<select name="gender"><option value="">Select gender</option><option value="male">Male</option><option value="female">Female</option><option value="other">Other</option></select></label>{field('Roll Number','rollNumber', 'text',false)}{refs()}{field('Section','section', 'text',false)}{field('Guardian Name','guardianName','text',false)}{field('Guardian Phone','guardianPhone','text',false)}{field('Guardian Email','guardianEmail','email',false)}</>;
    if(id==='teachers')return <>{field('First Name','firstName')}{field('Last Name','lastName')}{field('Email','email')}{field('Phone','phone', 'text',false)}{field('Qualification','qualification','text',false)}<fieldset className="multi-select"><legend>Subjects Handled</legend>{subjects.map(s=><label key={s._id}><input type="checkbox" name="subjectsHandled" value={name(s)}/>{name(s)}</label>)}</fieldset>{field('Joining Date','joiningDate','date',false)}</>;
    if(id==='timetables')return <>{refs()}<label>Day of Week<select name="dayOfWeek" required>{['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map(x=><option key={x}>{x}</option>)}</select></label><Periods periods={periods} setPeriods={setPeriods} subjects={classSubjects} teachers={teachers}/></>;
    if(id==='attendance')return <>{refs()}{field('Date','date','date')}<fieldset className="multi-select"><legend>Student attendance</legend>{classStudents.map(s=><label key={s._id}>{name(s)}<select value={attendance[s._id]??'present'} onChange={e=>setAttendance({...attendance,[s._id]:e.target.value})}><option value="present">Present</option><option value="absent">Absent</option><option value="leave">Leave</option></select></label>)}</fieldset></>;
    if(id==='exams')return <>{field('Name','name')}{refs()}{lookup('Subject','subjectId',classSubjects)}{field('Exam Date','examDate','date')}{field('Max Marks','maxMarks','number')}<label>Exam Type<select name="examType" required>{['unit-test','midterm','final','online-test'].map(x=><option key={x}>{x}</option>)}</select></label></>;
    if(id==='fees')return <>{refs()}{field('Academic Year','academicYear')}{field('Fee Type','feeType')}{field('Amount','amount','number')}{field('Due Date','dueDate','date')}</>;
    if(id==='leave'){const role='student';return <><label>Requester Type<select name="requesterType"><option value="student">Student</option><option value="teacher">Teacher</option></select></label>{lookup('Requester','requesterId',[...students,...teachers])}{field('From Date','fromDate','date')}{field('To Date','toDate','date')}<label className="full">Reason<textarea name="reason" required/></label></>}
    if(id==='admissions')return <>{field('Applicant First Name','applicantFirstName')}{field('Applicant Last Name','applicantLastName')}{field('Date of Birth','dateOfBirth','date')}<label>Gender<select name="gender"><option value="male">Male</option><option value="female">Female</option><option value="other">Other</option></select></label>{field('Guardian Name','guardianName')}{field('Guardian Contact','guardianContact')}{field('Guardian Email','guardianEmail','email')}{refs()}</>;
    if(id==='certificates')return <>{lookup('Student','studentId',students)}<label>Type<select name="type"><option value="id-card">ID Card</option><option value="bonafide">Bonafide</option><option value="transfer">Transfer</option></select></label></>;
    if(id==='notices')return <>{field('Title','title')}<label className="full">Message<textarea name="message" required/></label><label>Target Role<select name="targetRole"><option value="all">All</option><option value="student">Students</option><option value="teacher">Teachers</option><option value="parent">Parents</option><option value="admin">Admins</option></select></label>{lookup('Target Class','targetClassId',classes,false)}</>;
    if(id==='library')return <>{field('Title','title')}{field('Author','author')}{field('ISBN','isbn')}{field('Category','category')}{field('Total Copies','totalCopies','number')}</>;
    return <>{field('Route Name','routeName')}{field('Vehicle Number','vehicleNumber')}{field('Driver Name','driverName')}{field('Driver Contact','driverContact')}<Stops stops={stops} setStops={setStops}/></>}
  return <><div className="page-intro"><div><p>{title}</p><small>Data is loaded from <code>{endpoint}</code>.</small></div><div className="toolbar"><button className="secondary" onClick={()=>void load()}>Refresh</button><button className="primary" onClick={()=>setOpen(true)}>{action}</button></div></div>{open&&<section className="composer structured-composer"><div><h2>{action}</h2><p>Complete the fields below and send the request.</p></div><form className="structured-form" onSubmit={e=>void submit(e)}>{form()}<div className="form-actions"><button className="secondary" type="button" onClick={()=>setOpen(false)}>Cancel</button><button className="primary" disabled={busy}>{busy?'Sending…':'Send to API'}</button></div></form></section>}{error&&<div className="state error"><span>{error}</span></div>}<section className="data-card"><div className="data-top"><h2>Live records</h2><span>{rows.length} record(s)</span></div><div className="table-wrap"><table><tbody>{rows.map(r=><tr key={r._id}><td>{name(r)}</td></tr>)}</tbody></table></div></section></>;
}
function Periods({periods,setPeriods,subjects,teachers}:{periods:any[];setPeriods:(x:any[])=>void;subjects:Row[];teachers:Row[]}){return <fieldset className="multi-select"><legend>Periods</legend>{periods.map((p,i)=><div className="period-row" key={i}><input type="number" min="1" value={p.periodNumber} onChange={e=>setPeriods(periods.map((x,j)=>j===i?{...x,periodNumber:e.target.value}:x))}/><select value={p.subjectId} onChange={e=>setPeriods(periods.map((x,j)=>j===i?{...x,subjectId:e.target.value}:x))}><option value="">Subject</option>{subjects.map(s=><option value={s._id} key={s._id}>{name(s)}</option>)}</select><select value={p.teacherId} onChange={e=>setPeriods(periods.map((x,j)=>j===i?{...x,teacherId:e.target.value}:x))}><option value="">Teacher</option>{teachers.map(t=><option value={t._id} key={t._id}>{name(t)}</option>)}</select><input type="time" value={p.startTime} onChange={e=>setPeriods(periods.map((x,j)=>j===i?{...x,startTime:e.target.value}:x))}/><input type="time" value={p.endTime} onChange={e=>setPeriods(periods.map((x,j)=>j===i?{...x,endTime:e.target.value}:x))}/></div>)}<button type="button" className="secondary" onClick={()=>setPeriods([...periods,{periodNumber:periods.length+1,subjectId:'',teacherId:'',startTime:'09:00',endTime:'09:45'}])}>Add period</button></fieldset>}
function Stops({stops,setStops}:{stops:any[];setStops:(x:any[])=>void}){return <fieldset className="multi-select"><legend>Stops</legend>{stops.map((s,i)=><div className="period-row" key={i}><input placeholder="Stop name" value={s.stopName} onChange={e=>setStops(stops.map((x,j)=>j===i?{...x,stopName:e.target.value}:x))}/><input type="time" value={s.pickupTime} onChange={e=>setStops(stops.map((x,j)=>j===i?{...x,pickupTime:e.target.value}:x))}/></div>)}<button type="button" className="secondary" onClick={()=>setStops([...stops,{stopName:'',pickupTime:'07:30'}])}>Add stop</button></fieldset>}
