import { useEffect, useState } from 'react';
import { getStudents } from '../services/students.service';
import type { PaginatedStudents, Student, StudentQuery } from '../types/student.types';
import { StudentStatusBadge } from './StudentStatusBadge';
import './StudentsTable.css';

export function StudentList({ onSelect, onEdit, onDelete }: { onSelect?: (id: string) => void; onEdit?: (id: string) => void; onDelete?: (id: string) => void }) {
  const [result, setResult] = useState<PaginatedStudents>(); const [query, setQuery] = useState<StudentQuery>({ page: 1, limit: 20 }); const [error, setError] = useState('');
  const load = () => { setError(''); setResult(undefined); getStudents(query).then(setResult).catch(() => setError('Unable to load students. Something went wrong while fetching student records.')); };
  useEffect(load, [query]);
  const clear = () => setQuery({ page: 1, limit: 20 });
  if (error) return <div className="students-state students-state--error"><strong>Unable to load students</strong><p>{error}</p><button className="students-secondary-button" onClick={load}>Try Again</button></div>;
  if (!result) return <div className="students-skeleton"><i /><i /><i /><i /><i /></div>;
  const active = result.data.filter((student) => student.status === 'active').length; const inactive = result.data.filter((student) => student.status === 'inactive').length;
  return <section className="students-list-card"><div className="students-filter-bar"><input aria-label="Search students" placeholder="Search by student name, roll number or admission number" value={query.search ?? ''} onChange={(event) => setQuery({ ...query, search: event.target.value, page: 1 })} /><input aria-label="Filter class" placeholder="Class" value={query.class ?? ''} onChange={(event) => setQuery({ ...query, class: event.target.value, page: 1 })} /><input aria-label="Filter section" placeholder="Section" value={query.section ?? ''} onChange={(event) => setQuery({ ...query, section: event.target.value, page: 1 })} /><select aria-label="Student Status" value={query.status ?? ''} onChange={(event) => setQuery({ ...query, status: event.target.value as StudentQuery['status'], page: 1 })}><option value="">All Student Statuses</option><option value="active">Active</option><option value="inactive">Inactive</option><option value="transferred">Transferred</option><option value="graduated">Graduated</option></select><button className="students-secondary-button" onClick={clear}>Clear Filters</button></div><div className="students-table-title"><strong>{result.meta.total} students found</strong><span>Page {result.meta.page} · {active} active · {inactive} inactive</span></div>{result.data.length === 0 ? <div className="students-empty"><strong>No Students Found</strong><p>Start by registering your first student, or clear your search filters.</p><button className="students-secondary-button" onClick={clear}>Clear Filters</button></div> : <div className="students-table-wrap"><table><thead><tr><th>Student</th><th>Roll Number</th><th>Admission Number</th><th>Class</th><th>Section</th><th>Student Status</th><th>Actions</th></tr></thead><tbody>{result.data.map((student: Student) => <tr key={student._id}><td><div className="student-cell"><span>{student.firstName[0]}{student.lastName[0]}</span><div><b>{student.firstName} {student.lastName}</b><small>{student.email || 'No email provided'}</small></div></div></td><td>{student.rollNumber}</td><td>{student.admissionNumber}</td><td>{student.class}</td><td>{student.section}</td><td><StudentStatusBadge status={student.status} /></td><td><div className="students-row-actions"><button onClick={() => onSelect?.(student._id)}>View</button><button onClick={() => onEdit?.(student._id)}>Edit</button><button className="students-delete-action" onClick={() => onDelete?.(student._id)}>Delete</button></div></td></tr>)}</tbody></table></div>}<nav className="students-pagination" aria-label="Pagination"><button disabled={result.meta.page === 1} onClick={() => setQuery({ ...query, page: result.meta.page - 1 })}>Previous</button><span>Page {result.meta.page} of {result.meta.totalPages || 1}</span><button disabled={result.meta.page >= result.meta.totalPages} onClick={() => setQuery({ ...query, page: result.meta.page + 1 })}>Next</button></nav></section>;
}
