import { FormEvent, useEffect, useState } from 'react';
import { AppShell } from '../components/layout/AppShell';
import './CertificateGeneration.css';

const API = (import.meta.env.VITE_CERTIFICATE_SERVICE_URL as string | undefined) ?? 'http://localhost:3013';
type Certificate = { _id?: string; studentId: string; type?: string; issuedAt?: string; issuedBy?: string; referenceNo?: string };
type Tab = 'id' | 'bonafide' | 'transfer';
async function list(): Promise<Certificate[]> { let response: Response; try { response = await fetch(`${API}/certificates`); } catch { throw new Error(`Unable to reach the certificate service at ${API}.`); } const body: unknown = await response.json().catch(() => undefined); if (!response.ok) throw new Error(`Certificate service returned ${response.status}.`); return Array.isArray(body) ? body.filter((item): item is Certificate => typeof item === 'object' && item !== null && typeof (item as Certificate).studentId === 'string') : []; }
function date(value?: string) { if (!value) return '-'; const parsed = new Date(value); return Number.isNaN(parsed.getTime()) ? value : parsed.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }); }
export function CertificateGeneration() { const [items, setItems] = useState<Certificate[]>([]); const [tab, setTab] = useState<Tab>('id'); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [modal, setModal] = useState(false); const [saving, setSaving] = useState(false); const [selected, setSelected] = useState<Certificate>(); useEffect(() => { void list().then(setItems).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Unable to load certificates.')).finally(() => setLoading(false)); }, []); const visible = items.filter((item) => tab === 'id' || !item.type || item.type.toLowerCase().includes(tab === 'bonafide' ? 'bonafide' : 'transfer')); const current = selected ?? visible[0]; async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const data = { studentId: String(form.get('studentId') ?? '').trim(), type: String(form.get('type') ?? '').trim(), issuedAt: String(form.get('issuedAt') ?? ''), issuedBy: String(form.get('issuedBy') ?? '').trim(), referenceNo: String(form.get('referenceNo') ?? '').trim() }; if (!data.studentId || !data.type) return; setSaving(true); try { const response = await fetch(`${API}/certificates`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ data }) }); const created = await response.json() as Certificate; if (!response.ok) throw new Error(`Certificate service returned ${response.status}.`); setItems((old) => [...old, created]); setModal(false); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to create certificate.'); } finally { setSaving(false); } }
  return <AppShell title="Digital ID & Certificates" subtitle="Batch-generate security credentials, bonafide requests, and character certifications." activeNav="Certificates" showNavIcons><div className="certificate-actions"><button className="certificate-action-card" disabled><strong>▣ &nbsp; Generate ID Cards</strong><span>Not supported by the current service.</span></button><button className="certificate-action-card" onClick={() => setModal(true)}><strong>♙ &nbsp; Generate Certificates</strong><span>Create a certificate record.</span></button></div><div className="certificate-layout"><section className="certificate-card"><div className="certificate-toolbar"><div className="certificate-tabs">{(['id', 'bonafide', 'transfer'] as Tab[]).map((value) => <button key={value} className={tab === value ? 'is-active' : ''} onClick={() => setTab(value)}>{value === 'id' ? 'ID Cards' : value === 'bonafide' ? 'Certificates (Bonafide)' : 'Transfer Certs'}</button>)}</div><button className="certificate-batch" disabled>Batch Actions⌄</button></div>{loading && <p className="certificate-state">Loading certificates...</p>}{!loading && error && <p className="certificate-state certificate-state--error" role="alert">{error}</p>}{!loading && !error && <div className="certificate-table-wrap"><table className="certificate-table"><thead><tr><th>Student Name</th><th>Class</th><th>Roll No</th><th>Generated Date</th><th>Status</th></tr></thead><tbody>{visible.map((item) => <tr key={item._id ?? item.referenceNo ?? item.studentId} onClick={() => setSelected(item)}><th>{item.studentId}</th><td>-</td><td>-</td><td>{date(item.issuedAt)}</td><td><span className="certificate-badge">Generated</span></td></tr>)}</tbody></table>{visible.length === 0 && <p className="certificate-state">No certificate records are available.</p>}</div>}</section><aside className="certificate-preview"><h2>ID Template Preview</h2>{current ? <div className="certificate-preview-card"><strong>A &nbsp; ASTER ACADEMY</strong><b>{current.studentId.slice(0, 1).toUpperCase()}</b><strong>{current.studentId}</strong><small>Reference: {current.referenceNo ?? '-'}</small></div> : <p className="certificate-state">Preview unavailable.</p>}</aside></div>{modal && <div className="certificate-modal-backdrop"><form className="certificate-modal" onSubmit={(event) => void create(event)}><div className="certificate-modal-heading"><h2>Generate Certificate</h2><button type="button" onClick={() => setModal(false)}>×</button></div><label>Student ID<input name="studentId" required /></label><label>Certificate type<input name="type" required /></label><label>Issued date<input name="issuedAt" type="date" /></label><label>Issued by<input name="issuedBy" /></label><label>Reference number<input name="referenceNo" /></label><button className="certificate-primary" disabled={saving}>{saving ? 'Creating...' : 'Create Certificate'}</button></form></div>}</AppShell>; }
export default CertificateGeneration;