import { FormEvent, useEffect, useState } from 'react';
import { AppShell } from '../components/layout/AppShell';
import './Notices.css';

const API = (import.meta.env.VITE_NOTICE_SERVICE_URL as string | undefined) ?? 'http://localhost:3013';
type Notice = { _id?: string; title: string; body?: string; audience?: string[]; publishedAt?: string; authorId?: string };
async function listNotices(): Promise<Notice[]> { let response: Response; try { response = await fetch(`${API}/notices`); } catch { throw new Error(`Unable to reach the notice service at ${API}.`); } const body: unknown = await response.json().catch(() => undefined); if (!response.ok) throw new Error(`Notice service returned ${response.status}.`); return Array.isArray(body) ? body.filter((item): item is Notice => typeof item === 'object' && item !== null && typeof (item as Notice).title === 'string') : []; }
function date(value?: string) { if (!value) return '-'; const parsed = new Date(value); return Number.isNaN(parsed.getTime()) ? value : parsed.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }); }
export function Notices() { const [notices, setNotices] = useState<Notice[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [modal, setModal] = useState(false); const [saving, setSaving] = useState(false); useEffect(() => { void listNotices().then(setNotices).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Unable to load notices.')).finally(() => setLoading(false)); }, []); async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const data = { title: String(form.get('title') ?? '').trim(), body: String(form.get('body') ?? '').trim(), audience: String(form.get('audience') ?? '').split(',').map((item) => item.trim()).filter(Boolean), publishedAt: String(form.get('publishedAt') ?? ''), authorId: String(form.get('authorId') ?? '').trim() }; if (!data.title) return; setSaving(true); try { const response = await fetch(`${API}/notices`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ data }) }); const created = await response.json() as Notice; if (!response.ok) throw new Error(`Notice service returned ${response.status}.`); setNotices((current) => [...current, created]); setModal(false); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to create notice.'); } finally { setSaving(false); } }
  return <AppShell title="Notice Board" subtitle="Broadcast school timings, manage calendar events, and direct parents notices." activeNav="Notices" showNavIcons><div className="notice-heading"><h2>Active Notices</h2><button className="notice-primary" onClick={() => setModal(true)}>+ Create Notice</button></div><div className="notice-layout"><section className="notice-list">{loading && <p className="notice-state">Loading notices...</p>}{!loading && error && <p className="notice-state notice-state--error" role="alert">{error}</p>}{!loading && !error && notices.length === 0 && <p className="notice-state">No notices are available.</p>}{notices.map((notice) => <article className="notice-card" key={notice._id ?? `${notice.title}-${notice.publishedAt}`}><div className="notice-meta"><span className="notice-badge">Notice</span><span>Target: {notice.audience?.join(', ') || 'Unavailable'}</span><time>Published {date(notice.publishedAt)}</time></div><h3>{notice.title}</h3><p>{notice.body || '-'}</p><small>Author: {notice.authorId || 'Unavailable'}</small></article>)}</section><aside className="notice-side"><section><h2>Upcoming Events</h2><p className="notice-unavailable">Not supported by the notice service.</p></section><section><h2>Notice Statistics</h2><p className="notice-unavailable">Statistics are not exposed by the notice service.</p></section></aside></div>{modal && <div className="notice-modal-backdrop"><form className="notice-modal" onSubmit={(event) => void create(event)}><div className="notice-modal-heading"><h2>Create Notice</h2><button type="button" onClick={() => setModal(false)}>×</button></div><label>Title<input name="title" required /></label><label>Description<textarea name="body" rows={4} /></label><label>Audience<input name="audience" placeholder="Students, Parents" /></label><label>Published date<input name="publishedAt" type="date" /></label><label>Author ID<input name="authorId" /></label><button className="notice-primary" disabled={saving}>{saving ? 'Creating...' : 'Create Notice'}</button></form></div>}</AppShell>; }
export default Notices;
