import { FormEvent, useEffect, useState, type ReactNode } from 'react';
import './ReferenceScreens.css';

type ScreenProps = { title: string; subtitle: string; activeNav?: string; endpoint?: string; method?: 'GET' | 'POST'; children?: ReactNode };
const SERVICE_URLS: Record<string, string> = {
  dashboard: (import.meta.env.VITE_DASHBOARD_SERVICE_URL as string | undefined) ?? 'http://localhost:3016',
  teachers: (import.meta.env.VITE_TEACHER_SERVICE_URL as string | undefined) ?? 'http://localhost:3002',
  students: (import.meta.env.VITE_STUDENT_SERVICE_URL as string | undefined) ?? 'http://localhost:3001',
  transport: (import.meta.env.VITE_TRANSPORT_SERVICE_URL as string | undefined) ?? 'http://localhost:3012',
  auth: (import.meta.env.VITE_AUTH_SERVICE_URL as string | undefined) ?? 'http://localhost:3001',
};

export function ReferenceScreen({ title, subtitle, activeNav, endpoint, method = 'GET', children }: ScreenProps) {
  const [records, setRecords] = useState<unknown[]>([]); const [loading, setLoading] = useState(Boolean(endpoint)); const [error, setError] = useState<string | null>(null); const [query, setQuery] = useState(''); const [notice, setNotice] = useState<string | null>(null);
  useEffect(() => { if (!endpoint) return; const base = SERVICE_URLS[endpoint.split('/')[0]] ?? endpoint; void fetch(`${base}/${endpoint.split('/').slice(1).join('/')}`).then(async (response) => { const body = await response.json().catch(() => undefined); if (!response.ok) throw new Error(`Service returned ${response.status}.`); return body; }).then((body) => setRecords(Array.isArray(body) ? body : [body])).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Data unavailable.')).finally(() => setLoading(false)); }, [endpoint]);
  const filteredRecords = records.filter((record) => JSON.stringify(record).toLowerCase().includes(query.toLowerCase()));
  return <ReferenceShell title={title} activeNav={activeNav} query={query} onQueryChange={setQuery}><div className="reference-screen"><div className="reference-toolbar"><div><h2>{title}</h2><p>{subtitle}</p></div><button className="reference-primary" type="button" onClick={() => setNotice('This action is not exposed by the current backend service.')}>+ Create</button></div>{notice && <button className="reference-notice" type="button" onClick={() => setNotice(null)}>{notice} <b>Dismiss</b></button>}<div className="reference-metrics"><Metric label="Total" value={loading ? '...' : String(filteredRecords.length)} /><Metric label="Active" value={loading ? '...' : 'Unavailable'} /><Metric label="Pending" value="Unavailable" /><Metric label="Recent" value="Unavailable" /></div><section className="reference-panel">{loading && <State text="Loading live data..." />}{error && <State text={error} error />}{!loading && !error && endpoint && filteredRecords.length === 0 && <State text={query ? 'No records match your search.' : 'No records available.'} />}{!loading && !error && endpoint && filteredRecords.length > 0 && <DataTable records={filteredRecords} />}{!endpoint && <State text="This dashboard is not backed by a dedicated backend endpoint in the current project." />}{children}</section></div></ReferenceShell>;
}
function ReferenceShell({ title, activeNav, query, onQueryChange, children }: { title: string; activeNav?: string; query: string; onQueryChange: (value: string) => void; children: ReactNode }) { const [notificationsOpen, setNotificationsOpen] = useState(false); const groups = [['Overview', ['Dashboard']], ['Academics', ['Students', 'Teachers', 'Classes & Subjects', 'Timetable']], ['Engagement', ['Attendance', 'Assignments', 'Examinations', 'Performance']], ['Administration', ['Admissions', 'Fees', 'Leave Requests', 'Certificates', 'Auth & Roles']], ['Resources', ['Notices', 'Library', 'Transport']]]; return <div className="reference-shell"><aside className="reference-sidebar"><div className="reference-brand"><span>A</span><strong>Aster School<small>Admin portal</small></strong></div>{groups.map(([section, items]) => <div className="reference-nav-group" key={section}><small>{section}</small>{(items as string[]).map((item) => <div className={item === activeNav ? 'reference-nav-item is-active' : 'reference-nav-item'} key={item}>{item}</div>)}</div>)}<div className="reference-help"><b>Need help?</b><span>Visit the help center or contact school administration.</span></div></aside><main className="reference-main"><header className="reference-header"><div className="reference-header-title">{title}</div><div className="reference-header-actions"><label className="reference-global-search"><span>⌕</span><input value={query} onChange={(event) => onQueryChange(event.target.value)} placeholder="Search students, teachers..." /></label><div className="reference-notification-wrap"><button className="reference-icon-button" type="button" onClick={() => setNotificationsOpen((value) => !value)} aria-label="Notifications">♧</button>{notificationsOpen && <div className="reference-notifications">No new notifications.</div>}</div><span className="reference-avatar">OG</span><span className="reference-profile"><b>Olivia Grant</b><small>School administrator</small></span></div></header><div className="reference-content">{children}</div></main></div>; }
function Metric({ label, value }: { label: string; value: string }) { return <article className="reference-metric"><span>{label}</span><strong>{value}</strong><small>From available backend data</small></article>; }
function State({ text, error = false }: { text: string; error?: boolean }) { return <p className={error ? 'reference-state reference-state--error' : 'reference-state'}>{text}</p>; }
function DataTable({ records }: { records: unknown[] }) { const rows = records.filter((record): record is Record<string, unknown> => typeof record === 'object' && record !== null); const keys = [...new Set(rows.flatMap((row) => Object.keys(row).filter((key) => !['_id', '__v', 'createdAt', 'updatedAt'].includes(key))))].slice(0, 6); return <div className="reference-table-wrap"><table className="reference-table"><thead><tr>{keys.map((key) => <th key={key}>{key}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={String(row._id ?? index)}>{keys.map((key) => <td key={key}>{Array.isArray(row[key]) ? row[key].length : String(row[key] ?? '-')}</td>)}</tr>)}</tbody></table></div>; }

export function AuthForm() { const [message, setMessage] = useState(''); async function login(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { const response = await fetch(`${SERVICE_URLS.auth}/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: form.get('email'), password: form.get('password') }) }); setMessage(response.ok ? 'Signed in successfully.' : `Authentication returned ${response.status}.`); } catch { setMessage('Authentication service unavailable.'); } } return <div className="reference-auth"><form onSubmit={(event) => void login(event)}><div className="reference-brand">Aster School</div><h1>Welcome back</h1><p>Sign in to manage BrightBoard.</p><label>Email<input name="email" type="email" required /></label><label>Password<input name="password" type="password" required /></label><button className="reference-primary" type="submit">Sign in</button>{message && <small>{message}</small>}</form></div>; }